# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_lm <- function(y, X, w) {
    .Call(`_blblm_fast_lm`, y, X, w)
}

sample_intC <- function(df, m) {
    .Call(`_blblm_sample_intC`, df, m)
}

